//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarumt.WAM.Assignment.ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieVenueOngoingShowtime
    {
        public string MovieVenueId { get; set; }
        public string VenueLocation { get; set; }
        public Nullable<int> OngoingShowtimes { get; set; }
    }
}
