//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarumt.WAM.Assignment.ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieShowtimeTicketsSold
    {
        public string MovieShowtimeId { get; set; }
        public string ShowtimeName { get; set; }
        public string MovieId { get; set; }
        public string MovieName { get; set; }
        public Nullable<int> TicketsSold { get; set; }
    }
}
