//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarumt.WAM.Assignment.ERD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public string Id { get; set; }
        public string SeatNumbers { get; set; }
        public string MovieShowtimeId { get; set; }
        public int Status { get; set; }
        public string UserId { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual MovieShowtime MovieShowtime { get; set; }
        public virtual User User { get; set; }
    }
}
